In [2]:
# Imports for all mandatory exercises (so far)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## Exercise 03.04. (Assignment #01) 3D Linear Transformations

In [ ]:
# Define a set of points in 3D space
points = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]])

# Define a scaling transformation matrix
T_scale = np.array([
    [2, 0, 0],
    [0, 2, 0],
    [0, 0, 2]])

# Define a rotation transformation matrix
T_rotate = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]])

# Define a shearing transformation matrix
T_shear = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1]])

# Apply and display the transformed points
print("Original points:\n", points)

# Obs: to transform the points, points must be transposed to have the same dimensions as the transformation matrices
print("Scaled points:\n", np.dot(T_scale, (points.T)).T)
print("Rotated points:\n", np.dot(T_rotate, (points.T)).T)
print("Sheared points:\n", np.dot(T_shear, (points.T)).T)

'''
Scaling (uniform, 1=1=1): stretches the shape evenly, so it stays
proportional (a cube stays a cube, just bigger). Orientation is unaffected,
since no rotation occurs, edges/axes still point in the same direction.

Rotation (90 deg around z-axis): does not affect shape, since distances
between points (edge lengths) stay the same, only their position changes.
Orientation changes, since the object turns in the x-y plane.

Shear transformation: affects shape, since the x-value of a point determines how
much it gets pushed in the y-direction (higher x = more shift, x=0 = no shift).
This deforms the shape, so it no longer makes sense to talk about orientation.

Combining transformations: order does not matter when scaling is uniform,
since it scales all axes equally regardless of when it's applied. Order would matter with non-uniform scaling,
since different axes would be scaled differently depending on whether scaling happens before or after a shear or rotation transformation.
'''

## Exercise 03.05. (Assignment #01) Solving a System of Linear Equations (25-30 minutes)
Develop a Python script/notebook to solve a system of linear equations using matrices. Represent the system in matrix form $Ax = b$ and use NumPy to solve for the vector $x$. Display the solution and test the program with different systems of equations.

- Instructions:
    - Consider the system of equations:
    $$  2x + 3y = 5
        4x + y = 6 $$
    - Represent this system in matrix form $Ax = b$.
    - Use NumPy to solve for x (the vector [x, y]).
    - Display the solution.
    - Try different systems of equations to test the program.

In [30]:
# Define the coefficient matrix A and the constant matrix b
# A is the numbers before x and y (2x+3y=5) and (4x+y=6)
# b is what it is equal to so =5 and =6
A = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

print("Matrix A:\n ", A, sep="")
print("\nVector b:\n", b, sep="")

# Solve for x
x = np.linalg.solve(A, b)
print("\nSolve for x. \nSolution: \n", x)

#Try different systems of equations to test the program
def solve_equations(test_A,test_b):
    test_A = np.array(test_A)
    test_b = np.array(test_b)
    test_A_inv = np.linalg.inv(test_A)
    X = np.dot(test_A_inv, test_b)
    x, y = X

    print("\nMatrix A:\n", test_A, sep="")
    print("\nVector b:\n", test_b, sep="")
    print(f"\nSolution: \nx = {x:.2f} \ny = {y:.2f}")

# x + y = 10, x - y = 2
solve_equations([[1, 1], [1, -1]], [10, 2])

# 3x + 2y = 12, x - y = -1
solve_equations([[3, 2], [1, -1]], [12, -1])

Matrix A:
 [[2 3]
 [4 1]]

Vector b:
[5 6]

Solve for x. 
Solution: 
 [1.3 0.8]

Matrix A:
[[ 1  1]
 [ 1 -1]]

Vector b:
[10  2]

Solution: 
x = 6.00 
y = 4.00

Matrix A:
[[ 3  2]
 [ 1 -1]]

Vector b:
[12 -1]

Solution: 
x = 2.00 
y = 3.00


In [31]:
#Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations.

#Problem 1: Write a program that look at a collection (a list) of vectors of length D and find all
# possible bases if any, considering the exceptions:
# – “There are less than D independent vectors in the set.”
# – “The list of vectors contains vectors of different dimensions.”

import numpy as np
from itertools import combinations

def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.


## Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations. (20-45min)
– Review and implement algorithms to identify the most relevant components of vectors in spaces of interest.

_Problem 1:_
Write a program that look at a collection (a list) of vectors of length D and find all possible bases if any, considering the exceptions:
- “There are less than D independent vectors in the set.”
- “The list of vectors contains vectors of different dimensions.”

- Example Output:
        - for a list L = [[1,2,3,4],[5,6,7,8],[6,8,10,12],[4,4,4,4],[3,2,1,0]], the program should output:
            "There are less than D independent vectors in the set."

In [34]:
#Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations.

#Problem 1: Write a program that look at a collection (a list) of vectors of length D and find all
# possible bases if any, considering the exceptions:
# – “There are less than D independent vectors in the set.”
# – “The list of vectors contains vectors of different dimensions.”

import numpy as np
from itertools import combinations

def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.
