In [2]:
# Imports for all mandatory exercises (so far)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## Exercise 03.04. (Assignment #01) 3D Linear Transformations

In [ ]:
# Define a set of points in 3D space
points = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]])

# Define a scaling transformation matrix
T_scale = np.array([
    [2, 0, 0],
    [0, 2, 0],
    [0, 0, 2]])

# Define a rotation transformation matrix
T_rotate = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]])

# Define a shearing transformation matrix
T_shear = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1]])

# Apply and display the transformed points
print("Original points:\n", points)

# Obs: to transform the points, points must be transposed to have the same dimensions as the transformation matrices
print("Scaled points:\n", np.dot(T_scale, (points.T)).T)
print("Rotated points:\n", np.dot(T_rotate, (points.T)).T)
print("Sheared points:\n", np.dot(T_shear, (points.T)).T)

'''
Scaling (uniform, 1=1=1): stretches the shape evenly, so it stays
proportional (a cube stays a cube, just bigger). Orientation is unaffected,
since no rotation occurs, edges/axes still point in the same direction.

Rotation (90 deg around z-axis): does not affect shape, since distances
between points (edge lengths) stay the same, only their position changes.
Orientation changes, since the object turns in the x-y plane.

Shear transformation: affects shape, since the x-value of a point determines how
much it gets pushed in the y-direction (higher x = more shift, x=0 = no shift).
This deforms the shape, so it no longer makes sense to talk about orientation.

Combining transformations: order does not matter when scaling is uniform,
since it scales all axes equally regardless of when it's applied. Order would matter with non-uniform scaling,
since different axes would be scaled differently depending on whether scaling happens before or after a shear or rotation transformation.
'''

## Exercise 03.05. (Assignment #01) Solving a System of Linear Equations (25-30 minutes)
Develop a Python script/notebook to solve a system of linear equations using matrices. Represent the system in matrix form $Ax = b$ and use NumPy to solve for the vector $x$. Display the solution and test the program with different systems of equations.

- Instructions:
    - Consider the system of equations:
    $$  2x + 3y = 5
        4x + y = 6 $$
    - Represent this system in matrix form $Ax = b$.
    - Use NumPy to solve for x (the vector [x, y]).
    - Display the solution.
    - Try different systems of equations to test the program.

In [30]:
# Define the coefficient matrix A and the constant matrix b
# A is the numbers before x and y (2x+3y=5) and (4x+y=6)
# b is what it is equal to so =5 and =6
A = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

print("Matrix A:\n ", A, sep="")
print("\nVector b:\n", b, sep="")

# Solve for x
x = np.linalg.solve(A, b)
print("\nSolve for x. \nSolution: \n", x)

#Try different systems of equations to test the program
def solve_equations(test_A,test_b):
    test_A = np.array(test_A)
    test_b = np.array(test_b)
    test_A_inv = np.linalg.inv(test_A)
    X = np.dot(test_A_inv, test_b)
    x, y = X

    print("\nMatrix A:\n", test_A, sep="")
    print("\nVector b:\n", test_b, sep="")
    print(f"\nSolution: \nx = {x:.2f} \ny = {y:.2f}")

# x + y = 10, x - y = 2
solve_equations([[1, 1], [1, -1]], [10, 2])

# 3x + 2y = 12, x - y = -1
solve_equations([[3, 2], [1, -1]], [12, -1])

Matrix A:
 [[2 3]
 [4 1]]

Vector b:
[5 6]

Solve for x. 
Solution: 
 [1.3 0.8]

Matrix A:
[[ 1  1]
 [ 1 -1]]

Vector b:
[10  2]

Solution: 
x = 6.00 
y = 4.00

Matrix A:
[[ 3  2]
 [ 1 -1]]

Vector b:
[12 -1]

Solution: 
x = 2.00 
y = 3.00


In [31]:
#Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations.
from itertools import combinations

def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.


## Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations. (20-45min)
– Review and implement algorithms to identify the most relevant components of vectors in spaces of interest.

_Problem 1:_
Write a program that look at a collection (a list) of vectors of length D and find all possible bases if any, considering the exceptions:
- “There are less than D independent vectors in the set.”
- “The list of vectors contains vectors of different dimensions.”

- Example Output:
        - for a list L = [[1,2,3,4],[5,6,7,8],[6,8,10,12],[4,4,4,4],[3,2,1,0]], the program should output:
            "There are less than D independent vectors in the set."

In [34]:
#Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations.

#Problem 1: Write a program that look at a collection (a list) of vectors of length D and find all
# possible bases if any, considering the exceptions:
# – “There are less than D independent vectors in the set.”
# – “The list of vectors contains vectors of different dimensions.”

import numpy as np
from itertools import combinations

def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.


## Exercise 05.02. (Assignment #01) Descriptive Statistics

In [2]:
# Read Star Wars dataset into a dataframe
df = pd.read_csv("./exercises/starwars.csv")
print("Loaded dataset successfully")

# Handling missing data

# Numeric columns -> fill with that column's mean
num_cols = df.select_dtypes(include="number").columns
for c in num_cols:
    df[c] = df[c].fillna(df[c].mean())

# Categorical (non-numeric) columns -> fill with "Unknown"
cat_cols = df.select_dtypes(exclude="number").columns
for c in cat_cols:
    df[c] = df[c].fillna("Unknown")

# No missing values after cleaning dataset
print("Remaining missing values:", df.isna().sum().sum())   # -> 0
df.isna().sum()

# Descriptive summary of main characteristics for the Star Wars dataset.
raw = pd.read_csv("./exercises/starwars.csv")   # original, before imputation
cols = ["height", "mass", "birth_year"]          # the three numeric columns

summary = raw[cols].agg(["mean", "median", "std", "var"]).T
summary["mode"] = raw[cols].mode().iloc[0]       # first mode of each column
summary

NameError: name 'pd' is not defined

# Q1 — descriptive statistics
I selected the three numeric columns: `height`, `mass`, and `birth_year`.
Statistics were computed on the original data (before the 05.01 imputation),
since pandas skips missing values automatically and this avoids biasing the
results.

| Column     | Mean   | Median | Mode          | Std Dev | Variance  |
|------------|--------|--------|---------------|---------|-----------|
| height     | 174.60 | 180.00 | 183           | 34.77   | 1,209.24  |
| mass       | 97.31  | 79.00  | 80            | 169.46  | 28,715.73 |
| birth_year | 87.57  | 52.00  | 19 / 41.9 / 48| 154.69  | 23,929.44 |

`birth_year` is multimodal (three values tie), so its mode carries little meaning.

## Q2 — mean vs median
- height: mean (174.6) sits slightly below the median (180), a mild left skew.
  A cluster of short characters (droids, Yoda) drags the mean down.
- mass: mean (97.3) is far above the median (79), a strong right skew, driven
  almost entirely by Jabba the Hutt (1358 kg).
- birth_year: mean (87.6) is well above the median (52), again a strong right
  skew, caused by a few very old characters (Yoda 896, Jabba 600).

Rule of thumb: mean > median indicates right skew, mean < median indicates left
skew. Where the data is skewed, the median is the more trustworthy measure of
the "typical" value.

# Q3 — highest variability
By raw standard deviation and variance, `mass` is the most variable
(std 169.5, var 28,716), just ahead of `birth_year` (std 154.7, var 23,929).
`height` is far tighter (std 34.8).

Caveat: std and variance are scale-dependent, so comparing across columns with
different units (cm, kg, years) isn't strictly fair. Normalising by the mean
(coefficient of variation = std/mean) gives height = 0.20, mass = 1.74,
birth_year = 1.77  so relative to their own scale, mass and birth_year are
comparably dispersed and both far more variable than height.

# Q4 — outliers
- mass: Jabba the Hutt at 1358 kg is an extreme outlier — over 7x the median.
- birth_year: Yoda (896) and Jabba (600) sit far above the ~52-year median.
- height: Yarael Poof (264 cm) is a clear high outlier; the very short
  characters (Yoda 66, R2-D2 96) are genuine small droids/species, not errors.

Method note: I flagged values beyond mean ± 2 standard deviations. For `mass`
this is imperfect. Jabba's value so inflates the standard deviation that the
2 times std band only catches Jabba himself (the outlier masks its own detection).

# Missing-values effect (the reason for computing on original data)
Statistics were computed on the pre-imputation data. Had I used the 05.01
dataframe, where numeric gaps were filled with the column mean, the results
would be misleading:
- the mean is unchanged (mean-filling preserves it by construction);
- the variance and std shrink. Birth_year variance falls from 23,929 to
  11,686 (roughly halved), because every filled value sits exactly on the mean
  and adds no spread;
- the median is pulled toward the mean (birth_year median jumps 52 -> 87.6);
- the mode becomes the fill value itself (87.6).

Because `birth_year` and `mass` were 30-50%+ missing, imputing with the mean and
then measuring spread or shape would badly understate their true variability.
This is why descriptive statistics here are best taken from the original values.

In [ ]:
## Different answers

# Loading the dataset into a Pandas DataFrame
df = pd.read_csv("./starwars.csv")


# The three columns height, mass, and birth year are numerical columns that are relevant for statistical analysis.
# This was determined in exercise 05.01 by running the info() function on the dataframe.

# The selected numerical columns
num_col = ["height", "mass", "birth_year"]

# Using Pandas to calculate the descriptive statistics for each of the selected column
# print(df[num_col].describe())

for col in num_col:
    print(col, " statistics:")
    print("Mean: ", df[col].mean())
    print("Median: ", df[col].median())
    print("Mode: ", df[col].mode())
    print("Standard deviation: ", df[col].std())
    print("Variance: ", df[col].var(), "\n")

### 05.02 Questions & answers:

*OBS: Don't know if this should have been done on the cleaned data or not? - The following is on the original data*

**1. What are the mean, median, mode, standard deviation, and variance for the selected columns?**


|                    | Height             | Mass               | Birth year                               |
|--------------------|--------------------|--------------------|------------------------------------------|
| Mean               | 174.60493827160494 | 97.31186440677965  | 87.56511627906977                        |
| Median             | 180.0              | 79.0               | 52.0                                     |
| Mode               | 183.0              | 80.0               | 19.0, 41.9, 48.0, 52.0, 72.0, 82.0, 92.0 |
| Standard deviation | 34.774156715995886 | 169.45716281474404 | 154.69143923695466                       |
| Variance           | 1209.241975308642  | 28715.73002922267  | 23929.44137320044                        |



**2. Are there any significant differences between the mean and median? What does this tell you about the data distribution?**

For all three columns the mean and median differs. However, it is most significant for the birth year where the mean is approximately 88 and the median is 52. This indicates that there are a few very large observations that skews the mean. The same pattern is seen for mass but less severe.


**3. Based on the standard deviation and variance, which numerical column has the highest variability?**

The mass column has the highest standard deviation and variance and thus the highest variability.

**4. Are there any potential outliers in the data? If so, which columns and values?**

Both the mass and birth year column has a big variance which making it more likely for potential outliers. Looking at the statistic description potential outliers would most likely have a large value.


**Extra:**
**If there are missing values in the selected columns, describe how you handled them in Exercise 05.01 and how it may affect the computed statistics:**

There are missing values in the selected columns. Height has 6, mass has 28, and birth year has 44 missing values. In exercise 05.01 the missing values were handled by mean imputation such that all missing values were replaced by the calculated mean. Mean imputation most likely the right choice for the columns height and mass because they both have one mode close the mean and median, whereas birth year has many modes scattered across a large range. The mean and median for birth year also varies quite a bit making mean imputation potentially not represetive for missing data.


## Exercise 05.04. (Assignment #01) Categorical Data Exploration


In [ ]:
#Exercise 05.04. (Assignment #01)Categorical Data Exploration
import matplotlib.pyplot as plt

#Bar chart for species
species_count = data["species"].value_counts()

#plot = draw graph
species_count.plot(kind="bar")

#title and labels
plt.title("Number of characters per species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

#Grouped bar chart for gender distribution by species

# Crosstab Create a table with one row per species and one column per gender.
# Each cell contains the number of characters with that species and gender.
gender_by_species = pd.crosstab(data["species"], data["gender"])

gender_by_species.plot(kind="bar", color=["#999999", "#E07A9A", "#2580B7"])

plt.title("Gender distribution by species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.legend(title="Gender")
plt.show()

# 1. Which species has the most characters in the dataset?
# Humans

# 2. How does the gender distribution vary across species? Which an imbalanced gender ratio?
# There is a lot more with masculine than feminine genders in general.

# 3. Based on the bar charts, are there any species or species show gender categories that are underrepresented?
# Yes. Most species are represented by only one or two characters, while Human dominates the dataset.
# Across species, feminine characters are underrepresented compared to masculine characters.
# Many species have no feminine characters at all and a few have no masculine characters.


In [ ]:
# Setup tools for ydata_profiling
%pip install "setuptools<81"
# Makes it possible to show the report directly in the notebook.
# So ypu dont have to make a HTML file
%pip install ipywidgets

## Another solution to 05.04

In [ ]:
# Read Star Wars dataset into a dataframe
df = pd.read_csv("./exercises/starwars.csv")
print("Loaded dataset successfully")

# Clean the dataset
df['species'] = df['species'].fillna('Unknown')
df['gender'] = df['gender'].fillna('Unknown')

# Bar chart
species_counts = df['species'].value_counts()

fig, ax = plt.subplots(figsize=(12, 6))
species_counts.plot(kind='bar', ax=ax, color='steelblue', edgecolor='black')
ax.set_title('Number of Characters per Species in Star Wars', fontsize=14, fontweight='bold')
ax.set_xlabel('Species', fontsize=12)
ax.set_ylabel('Number of Characters', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('species_count.png', dpi=150)
plt.show()

## Categorical Data Exploration (Star Wars)

## Expected outputs/questions

### 1. Which species has the most characters?
Humans, around 35 characters. The next species,
Droid, only has about 6. So the dataset is heavily Human-dominated, and
everything else is a long tail.

### 2. How does gender distribution vary across species? Which show an imbalanced ratio?
Humans are basically the only species with a real gender mix, and even
they lean male (roughly 26 male to 9 female). Droids come out as mostly
`none` / masculine-coded. For every other species I can't really talk
about a "ratio". Most of them only have 1–2 characters, so any imbalance
is just an artifact of the tiny sample, not a real pattern. The one case
where an imbalance is actually meaningful is Humans, because that's the
only group with enough data to say anything.

### 3. Any underrepresented species or gender categories?
Female characters are underrepresented overall, only about 19 out of 87.
And nearly every non-Human species is underrepresented too, since most
show up just once. On the gender side, `hermaphroditic` and `none` / `n/a`
are edge cases.


## Exercise 05.06. (Assignment #01)

In [ ]:
import pandas as pd
import plotly.express as px
from ydata_profiling import ProfileReport

df = pd.read_csv("./exercises/starwars.csv")

df['species'] = df['species'].fillna('Unknown')
df['gender'] = df['gender'].fillna('Unknown')

# 1. Automated EDA report
profile = ProfileReport(df, title='Star Wars EDA Report', explorative=True)
profile.to_file('starwars_eda_report.html')

# 2. Interactive scatter: height vs mass
# height/mass are often read as strings/objects in this dataset — coerce them
df['height'] = pd.to_numeric(df['height'], errors='coerce')
df['mass']   = pd.to_numeric(df['mass'], errors='coerce')

fig_scatter = px.scatter(
    df, x='height', y='mass', color='species',
    hover_name='name',
    hover_data=['species', 'gender'],
    title='Height vs Mass by Species',
    labels={'height': 'Height (cm)', 'mass': 'Mass (kg)'}
)
fig_scatter.write_html('scatter_height_mass.html')
fig_scatter.show()

# 3. Interactive bar: species distribution
species_counts = df['species'].value_counts().reset_index()
species_counts.columns = ['species', 'count']

fig_bar = px.bar(
    species_counts, x='species', y='count',
    title='Character Count per Species',
    labels={'species': 'Species', 'count': 'Number of Characters'},
    hover_data={'count': True}
)
fig_bar.write_html('species_bar.html')
fig_bar.show()

## Another solution to 05.06

In [ ]:
# Exercise 05.06. (Assignment #01) Interactive Visualization and Exploratory Data Analysis

# Generate an Exploratory Data Analysis(EDA) report with Ydata profiling:
#This report will summarize the dataset’s structure, distribution, correlations, missing values, and potential outliers.

# Import the required libraries.
import plotly.express as px
from ydata_profiling import ProfileReport
import pandas as pd

#Load CSVfile:
starwars_data = pd.read_csv("../lecture05/exercises/starwars.csv")

# Create a profile report
profile = ProfileReport(starwars_data, title = "Star Wars Dataset Profiling Report", explorative=True)

# Show the report directly in the notebook as an embedded web page
profile.to_notebook_iframe()

#The other method where you make a HTML file
# Save the report to an HTML file
profile.to_file("starwars_report.html")

#The HTML file is save to the left in the same folder as this file

In [ ]:
# 05.06 Interactive scatter plot with Plotly: Create an interactive scatter plot to explore
# the relationship between height and mass using Plotly. Interactive plots allow you
# to hover over data points to view specific details and dynamically zoom in/out.

# Create an interactive scatter plot.
fig = px.scatter(
    starwars_data, x="height", y="mass", color="species",
    hover_name ="name",
    title="Interactive Star Wars Dataset Plot"
)
fig.show()

In [ ]:
# Create an interactive bar plot
fig = px.bar(
    species_count,
    #pandas automatically makes a "count" column when using value_counts()
    x="species", y="count",
    title="Distribution of Species in Star Wars"
)
fig.show()

### 05.06 Expected Output/Questions:
**1. What insights did the automated EDA report provide about the structure and quality of the dataset?**

The automated EDA report provides us information about the dataset such as that there are 20.4% missing cells and 0 duplictaed rows. Concerning the missing values the EDA report also provides three different visualization methods to quickly get an overview of the missing values and if there are any distinct patterns within the structure of the dataset. For example the mtrix over the missing values across all attributes enables you to quickly be able to get an overview without having to read each row.

**2. From the interactive scatter plot, do you notice any relationships between height and mass across species?**

Apart from the one outlier it seems like mass and height has a positive linear relation such that as height increases, mass increases proportionally.

**3. What do the interactive visualizations reveal about the distribution of categorical variables like species and gender?**


There are many more humans(35) than any other species and many species only have one character.

There are many more masculine(66) than feminine(17) characters in Star Wars.

**4. How do the interactive plots enhance your ability to explore the data compared to static plots?**

The interactive plots enhances the readibility of the plots by enabling zooming in and extracting exact numbers by the hovering functionionality. It also enables you to quickly and easily modify the plots such that the plots only show what is relevant for that instance.