In [2]:
# Imports for all mandatory exercises (so far)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## Exercise 03.04. (Assignment #01) 3D Linear Transformations

In [ ]:
# Define a set of points in 3D space
points = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]])

# Define a scaling transformation matrix
T_scale = np.array([
    [2, 0, 0],
    [0, 2, 0],
    [0, 0, 2]])

# Define a rotation transformation matrix
T_rotate = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]])

# Define a shearing transformation matrix
T_shear = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1]])

# Apply and display the transformed points
print("Original points:\n", points)

# Obs: to transform the points, points must be transposed to have the same dimensions as the transformation matrices
print("Scaled points:\n", np.dot(T_scale, (points.T)).T)
print("Rotated points:\n", np.dot(T_rotate, (points.T)).T)
print("Sheared points:\n", np.dot(T_shear, (points.T)).T)

'''
Scaling (uniform, 1=1=1): stretches the shape evenly, so it stays
proportional (a cube stays a cube, just bigger). Orientation is unaffected,
since no rotation occurs, edges/axes still point in the same direction.

Rotation (90 deg around z-axis): does not affect shape, since distances
between points (edge lengths) stay the same, only their position changes.
Orientation changes, since the object turns in the x-y plane.

Shear transformation: affects shape, since the x-value of a point determines how
much it gets pushed in the y-direction (higher x = more shift, x=0 = no shift).
This deforms the shape, so it no longer makes sense to talk about orientation.

Combining transformations: order does not matter when scaling is uniform,
since it scales all axes equally regardless of when it's applied. Order would matter with non-uniform scaling,
since different axes would be scaled differently depending on whether scaling happens before or after a shear or rotation transformation.
'''

## Exercise 03.05. (Assignment #01) Solving a System of Linear Equations (25-30 minutes)
Develop a Python script/notebook to solve a system of linear equations using matrices. Represent the system in matrix form $Ax = b$ and use NumPy to solve for the vector $x$. Display the solution and test the program with different systems of equations.

- Instructions:
    - Consider the system of equations:
    $$  2x + 3y = 5$$
    $$    4x + y = 6 $$
    - Represent this system in matrix form $Ax = b$.
    - Use NumPy to solve for x (the vector [x, y]).
    - Display the solution.
    - Try different systems of equations to test the program.

In [30]:
# Define the coefficient matrix A and the constant matrix b
# A is the numbers before x and y (2x+3y=5) and (4x+y=6)
# b is what it is equal to so =5 and =6
A = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

print("Matrix A:\n ", A, sep="")
print("\nVector b:\n", b, sep="")

# Solve for x
x = np.linalg.solve(A, b)
print("\nSolve for x. \nSolution: \n", x)

#Try different systems of equations to test the program
def solve_equations(test_A,test_b):
    test_A = np.array(test_A)
    test_b = np.array(test_b)
    test_A_inv = np.linalg.inv(test_A)
    X = np.dot(test_A_inv, test_b)
    x, y = X

    print("\nMatrix A:\n", test_A, sep="")
    print("\nVector b:\n", test_b, sep="")
    print(f"\nSolution: \nx = {x:.2f} \ny = {y:.2f}")

# x + y = 10, x - y = 2
solve_equations([[1, 1], [1, -1]], [10, 2])

# 3x + 2y = 12, x - y = -1
solve_equations([[3, 2], [1, -1]], [12, -1])

Matrix A:
 [[2 3]
 [4 1]]

Vector b:
[5 6]

Solve for x. 
Solution: 
 [1.3 0.8]

Matrix A:
[[ 1  1]
 [ 1 -1]]

Vector b:
[10  2]

Solution: 
x = 6.00 
y = 4.00

Matrix A:
[[ 3  2]
 [ 1 -1]]

Vector b:
[12 -1]

Solution: 
x = 2.00 
y = 3.00


# Exercise 03.07. (Assignment #01)
Grade Evaluation – Bases, Projections and Approximations.
from itertools import combinations

In [31]:
def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.


## Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations. (20-45min)
– Review and implement algorithms to identify the most relevant components of vectors in spaces of interest.

_Problem 1:_
Write a program that look at a collection (a list) of vectors of length D and find all possible bases if any, considering the exceptions:
- “There are less than D independent vectors in the set.”
- “The list of vectors contains vectors of different dimensions.”

- Example Output:
        - for a list L = [[1,2,3,4],[5,6,7,8],[6,8,10,12],[4,4,4,4],[3,2,1,0]], the program should output:
            "There are less than D independent vectors in the set."

In [34]:
#Exercise 03.07. (Assignment #01) Grade Evaluation – Bases, Projections and Approximations.

#Problem 1: Write a program that look at a collection (a list) of vectors of length D and find all
# possible bases if any, considering the exceptions:
# – “There are less than D independent vectors in the set.”
# – “The list of vectors contains vectors of different dimensions.”

import numpy as np
from itertools import combinations

def find_bases(L):

    # D is the length of the first vector, used as reference for the number of dimensions/number of axes. [1,2,3,4]=4
    D = len(L[0])

    # Check that all vectors have the same dimension
    same_dimension = True
    for vector in L:
        if len(vector) != D:
            same_dimension = False

    if not same_dimension:
        print(("The list of vectors contains vectors of different dimensions."))
    else:
        A = np.array(L)

        # Calculate the rank of matrix A
        # Rank is the number of directions your vectors actually cover, number of independent vectors.
        rank_A = np.linalg.matrix_rank(A)

        # Display the matrix and its rank
        print("Matrix A:")
        print(A)
        print("\nNumber of axes in the coordinate system (D):", D)
        print(f"\nNumber of independent vectors: {rank_A}")

        #To reach the whole space, you need as many different directions as the space has axes.
        if (rank_A < D):
            print("\nThere are less than D independent vectors in the set.")
        else:
            for group in combinations(L, D):
                if np.linalg.matrix_rank(np.array(group)) == D:
                    print("Base:", group)

# Example from the assignment
print("\nTest 1:")
find_bases([[1,2,3,4], [5,6,7,8], [6,8,10,12], [4,4,4,4], [3,2,1,0]])

# 3D with 4 vectors
print("\nTest 2:")
find_bases([[1,0,0], [0,1,0], [0,0,1], [1,1,0]])

# 2D with 3 vectors (expected: 3 bases, every pair works)
print("\nTest 3:")
find_bases([[1,0], [0,1], [1,1]])

# Different dimensions (expected: dimension error)
print("\nTest 4:")
find_bases([[1,2,3], [4,5], [6,7,8]])


Test 1:
Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 6  8 10 12]
 [ 4  4  4  4]
 [ 3  2  1  0]]

Number of axes in the coordinate system (D): 4

Number of independent vectors: 2

There are less than D independent vectors in the set.

Test 2:
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

Number of axes in the coordinate system (D): 3

Number of independent vectors: 3
Base: ([1, 0, 0], [0, 1, 0], [0, 0, 1])
Base: ([1, 0, 0], [0, 0, 1], [1, 1, 0])
Base: ([0, 1, 0], [0, 0, 1], [1, 1, 0])

Test 3:
Matrix A:
[[1 0]
 [0 1]
 [1 1]]

Number of axes in the coordinate system (D): 2

Number of independent vectors: 2
Base: ([1, 0], [0, 1])
Base: ([1, 0], [1, 1])
Base: ([0, 1], [1, 1])

Test 4:
The list of vectors contains vectors of different dimensions.


In [ ]:
#Problem 2: Write a program that calculates the projection of a vector over another,
# and returns the parallel component of the projected vector.

import numpy as np

def projection(v, w):
    #Make v and w into NumPy arrays
    v = np.array(v)
    w = np.array(w)

    # Find the length of w
    w_length = np.linalg.norm(w)

    # Find the direction of w: w divided by its length
    w_direction = w/w_length

    # Dot product between the direction and v (use np.dot)
    dot_product = np.dot(w_direction, v)

    # Multiply the dot product by the direction = the parallel component
    parallel = dot_product * w_direction

    # Return the result
    return parallel

# Example from the assignment
print(projection([1, 2, 3, 4], [0, 0, 1, 0]))

# Longer w, same direction
print(projection([1, 2, 3, 4], [0, 0, 5, 0]))

# Diagonal w in 2D
print(projection([3, 4], [1, 1]))


# How to read the result:
# w is the direction we measure along (the reference), v is the vector we ask about:
# how far does v get in w's direction?
# The result is an arrow from the origin (0, 0, 0, 0) to the point (0, 0, 3, 0).
# 3 in the 3rd place = v goes 3 steps along the 3rd axis, which is w's direction (this is the shadow).
# 0 = v goes 0 steps in that direction, because that part of v doesn't follow w.

In [ ]:
#Problem 3: Write a program that calculates the projection of a vector over a subspace generated by a list
# of given orthonormal vectors, and returns the parallel component of the projected vector

#subspace: Et subspace er alle de punkter, du kan nå ved at kombinere nogle bestemte vektorer

def projection_subspace(v, L):
    # Make v into a NumPy array
    v = np.array(v)

    # Start with a vector of zeros (same length as v) to collect the shadows
    total = np.zeros(len(v)) # [0, 0, 0, 0]

    # Loop through each vector e in L
    for e in L:
        # Make e into a NumPy array
        e = np.array(e)
        # Find the shadow of v on e (same as problem 2)
        shadow = projection(v, e)
        # Add the shadow to the total
        total = total + shadow

    # Return the total
    return total

# Orthonormal: 1st, 2nd and 4th axis
print(projection_subspace([2, 3, 4, 5], [[1,0,0,0], [0,1,0,0], [0,0,0,1]]))

# How to read the result:
# The subspace is spanned by the 1st, 2nd and 4th axis (the 3rd axis is not included).
# The result [2, 3, 0, 5] is the point in the subspace closest to v (v's shadow on the subspace).
# 2, 3 and 5 stay, because those parts of v follow the subspace's directions.
# 0, because v's part along the 3rd axis is orthogonal(at a right angle to) to the subspace, so it disappears.

## Exercise 05.02. (Assignment #01) Descriptive Statistics

In [2]:
# Read Star Wars dataset into a dataframe
df = pd.read_csv("./exercises/starwars.csv")
print("Loaded dataset successfully")

# Handling missing data

# Numeric columns -> fill with that column's mean
num_cols = df.select_dtypes(include="number").columns
for c in num_cols:
    df[c] = df[c].fillna(df[c].mean())

# Categorical (non-numeric) columns -> fill with "Unknown"
cat_cols = df.select_dtypes(exclude="number").columns
for c in cat_cols:
    df[c] = df[c].fillna("Unknown")

# No missing values after cleaning dataset
print("Remaining missing values:", df.isna().sum().sum())   # -> 0
df.isna().sum()

# Descriptive summary of main characteristics for the Star Wars dataset.
raw = pd.read_csv("./exercises/starwars.csv")   # original, before imputation
cols = ["height", "mass", "birth_year"]          # the three numeric columns

summary = raw[cols].agg(["mean", "median", "std", "var"]).T
summary["mode"] = raw[cols].mode().iloc[0]       # first mode of each column
summary

NameError: name 'pd' is not defined

# Q1 — descriptive statistics
I selected the three numeric columns: `height`, `mass`, and `birth_year`.
Statistics were computed on the original data (before the 05.01 imputation),
since pandas skips missing values automatically and this avoids biasing the
results.

| Column     | Mean   | Median | Mode          | Std Dev | Variance  |
|------------|--------|--------|---------------|---------|-----------|
| height     | 174.60 | 180.00 | 183           | 34.77   | 1,209.24  |
| mass       | 97.31  | 79.00  | 80            | 169.46  | 28,715.73 |
| birth_year | 87.57  | 52.00  | 19 / 41.9 / 48| 154.69  | 23,929.44 |

`birth_year` is multimodal (three values tie), so its mode carries little meaning.

## Q2 — mean vs median
- height: mean (174.6) sits slightly below the median (180), a mild left skew.
  A cluster of short characters (droids, Yoda) drags the mean down.
- mass: mean (97.3) is far above the median (79), a strong right skew, driven
  almost entirely by Jabba the Hutt (1358 kg).
- birth_year: mean (87.6) is well above the median (52), again a strong right
  skew, caused by a few very old characters (Yoda 896, Jabba 600).

Rule of thumb: mean > median indicates right skew, mean < median indicates left
skew. Where the data is skewed, the median is the more trustworthy measure of
the "typical" value.

# Q3 — highest variability
By raw standard deviation and variance, `mass` is the most variable
(std 169.5, var 28,716), just ahead of `birth_year` (std 154.7, var 23,929).
`height` is far tighter (std 34.8).

Caveat: std and variance are scale-dependent, so comparing across columns with
different units (cm, kg, years) isn't strictly fair. Normalising by the mean
(coefficient of variation = std/mean) gives height = 0.20, mass = 1.74,
birth_year = 1.77  so relative to their own scale, mass and birth_year are
comparably dispersed and both far more variable than height.

# Q4 — outliers
- mass: Jabba the Hutt at 1358 kg is an extreme outlier — over 7x the median.
- birth_year: Yoda (896) and Jabba (600) sit far above the ~52-year median.
- height: Yarael Poof (264 cm) is a clear high outlier; the very short
  characters (Yoda 66, R2-D2 96) are genuine small droids/species, not errors.

Method note: I flagged values beyond mean ± 2 standard deviations. For `mass`
this is imperfect. Jabba's value so inflates the standard deviation that the
2 times std band only catches Jabba himself (the outlier masks its own detection).

# Missing-values effect (the reason for computing on original data)
Statistics were computed on the pre-imputation data. Had I used the 05.01
dataframe, where numeric gaps were filled with the column mean, the results
would be misleading:
- the mean is unchanged (mean-filling preserves it by construction);
- the variance and std shrink. Birth_year variance falls from 23,929 to
  11,686 (roughly halved), because every filled value sits exactly on the mean
  and adds no spread;
- the median is pulled toward the mean (birth_year median jumps 52 -> 87.6);
- the mode becomes the fill value itself (87.6).

Because `birth_year` and `mass` were 30-50%+ missing, imputing with the mean and
then measuring spread or shape would badly understate their true variability.
This is why descriptive statistics here are best taken from the original values.

## Exercise 05.04. (Assignment #01) Categorical Data Exploration


In [ ]:
#Exercise 05.04. (Assignment #01)Categorical Data Exploration
import matplotlib.pyplot as plt

#Bar chart for species
species_count = data["species"].value_counts()

#plot = draw graph
species_count.plot(kind="bar")

#title and labels
plt.title("Number of characters per species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

#Grouped bar chart for gender distribution by species

# Crosstab Create a table with one row per species and one column per gender.
# Each cell contains the number of characters with that species and gender.
gender_by_species = pd.crosstab(data["species"], data["gender"])

gender_by_species.plot(kind="bar", color=["#999999", "#E07A9A", "#2580B7"])

plt.title("Gender distribution by species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.legend(title="Gender")
plt.show()

In [ ]:
# Setup tools for ydata_profiling
%pip install "setuptools<81"
# Makes it possible to show the report directly in the notebook.
# So ypu dont have to make a HTML file
%pip install ipywidgets

## Categorical Data Exploration (Star Wars)

## Expected outputs/questions

### 1. Which species has the most characters?
Humans, around 35 characters. The next species,
Droid, only has about 6. So the dataset is heavily Human-dominated, and
everything else is a long tail.

### 2. How does gender distribution vary across species? Which show an imbalanced ratio?
Humans are basically the only species with a real gender mix, and even
they lean male (roughly 26 male to 9 female). Droids come out as mostly
`none` / masculine-coded. For every other species I can't really talk
about a "ratio". Most of them only have 1–2 characters, so any imbalance
is just an artifact of the tiny sample, not a real pattern. The one case
where an imbalance is actually meaningful is Humans, because that's the
only group with enough data to say anything.

### 3. Any underrepresented species or gender categories?
Female characters are underrepresented overall, only about 19 out of 87.
And nearly every non-Human species is underrepresented too, since most
show up just once. On the gender side, `hermaphroditic` and `none` / `n/a`
are edge cases.


## Exercise 05.06. (Assignment #01)

In [ ]:
import pandas as pd
import plotly.express as px
from ydata_profiling import ProfileReport

df = pd.read_csv("./starwars.csv")

df['species'] = df['species'].fillna('Unknown')
df['gender'] = df['gender'].fillna('Unknown')

# 1. Automated EDA report
profile = ProfileReport(df, title='Star Wars EDA Report', explorative=True)
profile.to_file('starwars_eda_report.html')

# 2. Interactive scatter: height vs mass
# height/mass are often read as strings/objects in this dataset — coerce them
df['height'] = pd.to_numeric(df['height'], errors='coerce')
df['mass']   = pd.to_numeric(df['mass'], errors='coerce')

fig_scatter = px.scatter(
    df, x='height', y='mass', color='species',
    hover_name='name',
    hover_data=['species', 'gender'],
    title='Height vs Mass by Species',
    labels={'height': 'Height (cm)', 'mass': 'Mass (kg)'}
)
fig_scatter.write_html('scatter_height_mass.html')
fig_scatter.show()

# 3. Interactive bar: species distribution
species_counts = df['species'].value_counts().reset_index()
species_counts.columns = ['species', 'count']

fig_bar = px.bar(
    species_counts, x='species', y='count',
    title='Character Count per Species',
    labels={'species': 'Species', 'count': 'Number of Characters'},
    hover_data={'count': True}
)
fig_bar.write_html('species_bar.html')
fig_bar.show()

C:\Users\dp\AppData\Local\miniforge3\envs\damml2026\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### 05.06 Expected Output/Questions:
**1. What insights did the automated EDA report provide about the structure and quality of the dataset?**

The automated EDA report provides us information about the dataset such as that there are 20.4% missing cells and 0 duplictaed rows. Concerning the missing values the EDA report also provides three different visualization methods to quickly get an overview of the missing values and if there are any distinct patterns within the structure of the dataset. For example the mtrix over the missing values across all attributes enables you to quickly be able to get an overview without having to read each row.

**2. From the interactive scatter plot, do you notice any relationships between height and mass across species?**

Apart from the one outlier it seems like mass and height has a positive linear relation such that as height increases, mass increases proportionally.

**3. What do the interactive visualizations reveal about the distribution of categorical variables like species and gender?**


There are many more humans(35) than any other species and many species only have one character.

There are many more masculine(66) than feminine(17) characters in Star Wars.

**4. How do the interactive plots enhance your ability to explore the data compared to static plots?**

The interactive plots enhances the readibility of the plots by enabling zooming in and extracting exact numbers by the hovering functionionality. It also enables you to quickly and easily modify the plots such that the plots only show what is relevant for that instance.