## Exercise 03.02

* Matrix Operations (20-25 minutes) – Develop a Python script/notebook
to perform basic operations on matrices. The program should create two matrices and
compute their sum, difference, product, and transpose. Use Python lists or NumPy arrays
to represent the matrices.

In [1]:
import numpy as np
import matplotlib as plt

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C_addition = A + B
C_subtraction = A - B
C_mp = np.matmul(A, B)
C_A_transpose = A.T
C_B_transpose = B.T

print(C_addition)
print(C_subtraction)
print(C_mp)
print(C_A_transpose)
print(C_B_transpose)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


## Exercise 03.03
2D Linear Transformation (20-30 minutes) – Write a Python script/note-
book that applies a linear transformation to a set of 2D points. Define a 2×2 transformation
matrix (e.g., rotation or scaling matrix) and apply it to a list of 2D points. Display the orig-
inal and transformed points.

In [3]:
T = np.array([[0, -1],[1,0]])
points = [(1,1),(2,2),(3,3)]

transformed = [tuple(T @ np.array(p)) for p in points]

print(points)
print(transformed)

[(1, 1), (2, 2), (3, 3)]
[(np.int64(-1), np.int64(1)), (np.int64(-2), np.int64(2)), (np.int64(-3), np.int64(3))]


In [9]:
T = np.array([[4, 0],[0,3]])
points = [(1,1),(2,2),(3,3)]

transformed = [tuple(T @ np.array(p)) for p in points]

print(points)
print(transformed)

[(1, 1), (2, 2), (3, 3)]
[(np.int64(4), np.int64(3)), (np.int64(8), np.int64(6)), (np.int64(12), np.int64(9))]


## Exercise 03.04
(Assignment #01) 3D Linear Transformations (30-35 minutes) – In this
exercise, you will explore the concept of linear transformations in three dimensions. You will
implement various 3D transformations using matrices and visualize their effects on a set of
points in three-dimensional space. You will define and apply different linear transformations,
such as scaling, rotation, and shearing, to a set of 3D points. The exercise will help you
understand how linear transformations can manipulate objects in three-dimensional space.

In [11]:
# 8x3 matrix
points = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1],
])

T_scale = np.array([
    [2, 0, 0],
    [0, 2, 0],
    [0, 0, 2],
])

T_rotate = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1],
])

T_shear = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1],
])

scaled = points @ T_scale.T
rotated = points @ T_rotate.T
sheared = points @ T_shear.T

print(scaled)
print()
print(rotated)
print()
print(sheared)

[[0 0 0]
 [2 0 0]
 [2 2 0]
 [0 2 0]
 [0 0 2]
 [2 0 2]
 [2 2 2]
 [0 2 2]]

[[ 0  0  0]
 [ 0  1  0]
 [-1  1  0]
 [-1  0  0]
 [ 0  0  1]
 [ 0  1  1]
 [-1  1  1]
 [-1  0  1]]

[[0 0 0]
 [1 1 0]
 [1 2 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 2 1]
 [0 1 1]]


## Exercise 03.05 (Assignment #01)
 Solving a System of Linear Equations (25-30 minutes)
– Develop a Python script/notebook to solve a system of linear equations using matrices.
Represent the system in matrix form Ax = b and use NumPy to solve for the vector x.
Display the solution and test the program with different systems of equations.

In [25]:
import numpy as np

A = np.array([[2, 3],
              [4, 1]])
B = np.array([5, 6])

#Solve for x
x = np.linalg.solve(A, B)

print(x)
print(f"x = {x[0]}, y = {x[1]}")

print()

A2 = np.array([[2, 8],
               [1, -2]])
B2 = np.array([10, 2])
x2 = np.linalg.solve(A2, B2)

print(x2)
print(f"x = {x2[0]}, y = {x2[1]}")

[1.3 0.8]
x = 1.3, y = 0.8

[3.  0.5]
x = 3.0, y = 0.5
